[package]
name = "secure-tunnel-compatibility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[test]]
name = "compatibility"
path = "compatibility.rs"

[dev-dependencies]
base64.workspace = true
secure-tunnel = { path = "../../crates/secure-tunnel" }
